/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.controlGame;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 0068961
 */
public class FrameApp extends javax.swing.JFrame {

    Random gen = new Random();
    controlGame ControleJogo;
    
    
    public FrameApp() {
        initComponents();
        Config();
        
    }

    public void Config(){
        this.ControleJogo = new controlGame();
        String nome = JOptionPane.showInputDialog("Informe seu Nome:");
        if(nome.isEmpty()){
            nome = "Player 1";
        }
        nomePlayerTxt.setText(nome);
    }
    
    public void jogo(int jogadaPlayer){
        int jogadaCPU = gen.nextInt(1, 4);
        this.ControleJogo.rodada(jogadaPlayer, jogadaCPU, jogadaPlayerTxt,
                jogadaCPUTxt, rodadaList, nomePlayerTxt.getText(),
                placarPlayer, placarCPU);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rodadaList = new javax.swing.JList<>();
        placarTxt1 = new javax.swing.JLabel();
        nomePlayerTxt = new javax.swing.JLabel();
        historicoTxt = new javax.swing.JLabel();
        nomeCpuTxt = new javax.swing.JLabel();
        placarTxt = new javax.swing.JLabel();
        placarCPU = new javax.swing.JLabel();
        placarPlayer = new javax.swing.JLabel();
        jogadaCPUTxt = new javax.swing.JLabel();
        jogadatxt1 = new javax.swing.JLabel();
        jogadatxt = new javax.swing.JLabel();
        jogadaPlayerTxt = new javax.swing.JLabel();
        tesouraB = new javax.swing.JButton();
        pedraB = new javax.swing.JButton();
        papelB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jokenpo");
        setPreferredSize(new java.awt.Dimension(800, 462));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        rodadaList.setBackground(new java.awt.Color(153, 153, 255));
        rodadaList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        rodadaList.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rodadaList.setForeground(new java.awt.Color(255, 255, 255));
        rodadaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rodadaList.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(rodadaList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(270, 104, 258, 220);

        placarTxt1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        placarTxt1.setForeground(new java.awt.Color(102, 51, 255));
        placarTxt1.setText("Placar");
        jPanel1.add(placarTxt1);
        placarTxt1.setBounds(630, 100, 60, 32);

        nomePlayerTxt.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nomePlayerTxt.setForeground(new java.awt.Color(102, 51, 255));
        nomePlayerTxt.setText("Nome");
        jPanel1.add(nomePlayerTxt);
        nomePlayerTxt.setBounds(90, 30, 160, 32);

        historicoTxt.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        historicoTxt.setForeground(new java.awt.Color(102, 51, 255));
        historicoTxt.setText("HISTÓRICO");
        jPanel1.add(historicoTxt);
        historicoTxt.setBounds(330, 66, 132, 32);

        nomeCpuTxt.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nomeCpuTxt.setForeground(new java.awt.Color(102, 51, 255));
        nomeCpuTxt.setText("CPU");
        jPanel1.add(nomeCpuTxt);
        nomeCpuTxt.setBounds(630, 30, 50, 32);

        placarTxt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        placarTxt.setForeground(new java.awt.Color(102, 51, 255));
        placarTxt.setText("Placar");
        jPanel1.add(placarTxt);
        placarTxt.setBounds(90, 110, 51, 24);

        placarCPU.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        placarCPU.setForeground(new java.awt.Color(102, 51, 255));
        placarCPU.setText("0");
        jPanel1.add(placarCPU);
        placarCPU.setBounds(650, 150, 13, 32);

        placarPlayer.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        placarPlayer.setForeground(new java.awt.Color(102, 51, 255));
        placarPlayer.setText("0");
        jPanel1.add(placarPlayer);
        placarPlayer.setBounds(110, 150, 13, 32);

        jogadaCPUTxt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jogadaCPUTxt.setForeground(new java.awt.Color(102, 51, 255));
        jogadaCPUTxt.setText("Nenhuma");
        jPanel1.add(jogadaCPUTxt);
        jogadaCPUTxt.setBounds(660, 290, 109, 20);

        jogadatxt1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jogadatxt1.setForeground(new java.awt.Color(102, 51, 255));
        jogadatxt1.setText("Jogada:");
        jPanel1.add(jogadatxt1);
        jogadatxt1.setBounds(50, 290, 70, 24);

        jogadatxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jogadatxt.setForeground(new java.awt.Color(102, 51, 255));
        jogadatxt.setText("Jogada:");
        jPanel1.add(jogadatxt);
        jogadatxt.setBounds(580, 290, 70, 24);

        jogadaPlayerTxt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jogadaPlayerTxt.setForeground(new java.awt.Color(102, 51, 255));
        jogadaPlayerTxt.setText("Nenhuma");
        jPanel1.add(jogadaPlayerTxt);
        jogadaPlayerTxt.setBounds(130, 290, 77, 20);

        tesouraB.setBackground(new java.awt.Color(102, 102, 255));
        tesouraB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tesouraB.setForeground(new java.awt.Color(102, 102, 255));
        tesouraB.setText("TESOURA");
        tesouraB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        tesouraB.setContentAreaFilled(false);
        tesouraB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesouraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesouraBActionPerformed(evt);
            }
        });
        jPanel1.add(tesouraB);
        tesouraB.setBounds(290, 370, 120, 30);

        pedraB.setBackground(new java.awt.Color(102, 102, 255));
        pedraB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pedraB.setForeground(new java.awt.Color(102, 102, 255));
        pedraB.setText("PEDRA");
        pedraB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        pedraB.setContentAreaFilled(false);
        pedraB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pedraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraBActionPerformed(evt);
            }
        });
        jPanel1.add(pedraB);
        pedraB.setBounds(30, 370, 120, 30);

        papelB.setBackground(new java.awt.Color(102, 102, 255));
        papelB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        papelB.setForeground(new java.awt.Color(102, 102, 255));
        papelB.setText("PAPEL");
        papelB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        papelB.setContentAreaFilled(false);
        papelB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        papelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelBActionPerformed(evt);
            }
        });
        jPanel1.add(papelB);
        papelB.setBounds(160, 370, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pedraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraBActionPerformed
        jogo(1);
    }//GEN-LAST:event_pedraBActionPerformed

    private void papelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelBActionPerformed
        jogo(2);
    }//GEN-LAST:event_papelBActionPerformed

    private void tesouraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesouraBActionPerformed
        jogo(3);
    }//GEN-LAST:event_tesouraBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel historicoTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jogadaCPUTxt;
    private javax.swing.JLabel jogadaPlayerTxt;
    private javax.swing.JLabel jogadatxt;
    private javax.swing.JLabel jogadatxt1;
    private javax.swing.JLabel nomeCpuTxt;
    private javax.swing.JLabel nomePlayerTxt;
    private javax.swing.JButton papelB;
    private javax.swing.JButton pedraB;
    private javax.swing.JLabel placarCPU;
    private javax.swing.JLabel placarPlayer;
    private javax.swing.JLabel placarTxt;
    private javax.swing.JLabel placarTxt1;
    private javax.swing.JList<String> rodadaList;
    private javax.swing.JButton tesouraB;
    // End of variables declaration//GEN-END:variables
}
